package com.example.demospring1.service.enums;

public enum RoleName {

    ROLE_USER,
    ROLE_ADMIN,
    ROLE_MODERATOR,
    ROLE_LIBRARIAN,
    ROLE_PUBLISHER,
    ROLE_AUTHOR,
    ROLE_READER,
    ROLE_EDITOR,
    ROLE_MEMBER,
    ROLE_GUEST,
    ROLE_CONTRIBUTOR,
    ROLE_VIEWER,
    ROLE_MANAGER,
    ROLE_SUPERVISOR,
    ROLE_COORDINATOR,
    ROLE_DIRECTOR
}
